_wandb:
    value:
        cli_version: 0.21.0
        e:
            dwzf4bpse1hpjr4l4kbiglukezupeyzu:
                codePath: 9-Wandb-visualization/.local/wandb_laptop_multicore_benchmark.py
                codePathLocal: 9-Wandb-visualization/.local/wandb_laptop_multicore_benchmark.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "67108864"
                        used: "16384"
                email: kim.takala@hotmail.com
                executable: /opt/miniconda3/envs/pytorch/bin/python3
                git:
                    commit: 1254073679aa71813a99167bba8874a89058bae0
                host: ampuhaukka.lnx.csc.fi
                memory:
                    total: "16211910656"
                os: Linux-5.14.0-570.25.1.el9_6.x86_64-x86_64-with-glibc2.31
                program: /home/takalaki/Projects/LUMI-AI-Guide-COPY/9-Wandb-visualization/.local/wandb_laptop_multicore_benchmark.py
                python: CPython 3.12.4
                root: /home/takalaki/Projects/LUMI-AI-Guide-COPY
                startedAt: "2025-07-14T13:23:57.719894Z"
                writerId: dwzf4bpse1hpjr4l4kbiglukezupeyzu
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.4
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
architecture:
    value: vit_b_16
batch_size:
    value: 16
cpu_cores:
    value: 8
cpu_count:
    value: 8
cpu_count_logical:
    value: 8
cpu_freq:
    value: 4226.474875
cpu_model:
    value: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
device_type:
    value: CPU
epochs:
    value: 3
learning_rate:
    value: 0.001
memory_total_gb:
    value: 15.098518371582031
platform:
    value: Linux-5.14.0-570.25.1.el9_6.x86_64-x86_64-with-glibc2.31
processor:
    value: x86_64
python_version:
    value: 3.12.4
pytorch_threads:
    value: 8
pytorch_version:
    value: 2.4.1+rocm6.1
scaling_strategy:
    value: multi_core_cpu
subset_percentage:
    value: 2
